# Generated by Django 5.1.2 on 2025-02-08 18:44

import django.db.models.deletion
import store_settings.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StoreSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "store_name",
                    models.CharField(
                        default="Little Explorers", max_length=255
                    ),
                ),
                (
                    "store_logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="store_logos/"
                    ),
                ),
                (
                    "main_page_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="main_page_image/"
                    ),
                ),
                (
                    "welcome_msg",
                    models.CharField(
                        default="Welcome to our store", max_length=255
                    ),
                ),
                (
                    "home_page_button",
                    models.CharField(default="Discover More", max_length=20),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        default="IrishRoyals@example.com", max_length=254
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(default="+353000000000", max_length=20),
                ),
                ("currency", models.CharField(default="EUR", max_length=10)),
                ("enable_reviews", models.BooleanField(default=True)),
                (
                    "enable_maintenance_mode",
                    models.BooleanField(default=False),
                ),
                ("enable_paypal", models.BooleanField(default=True)),
                ("enable_stripe", models.BooleanField(default=True)),
                (
                    "enable_cash_on_delivery",
                    models.BooleanField(default=True),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        default=1,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="store_settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Store Settings",
                "verbose_name_plural": "Store Settings",
            },
        ),
        migrations.CreateModel(
            name="ShippingSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "shipping_options",
                    models.IntegerField(
                        choices=[
                            (1, "Standard Shipping"),
                            (2, "Express Shipping"),
                            (3, "Free Shipping"),
                        ],
                        default=1,
                    ),
                ),
                (
                    "standard_shipping_cost",
                    models.DecimalField(
                        decimal_places=2, default=5.0, max_digits=6
                    ),
                ),
                (
                    "free_shipping_threshold",
                    models.DecimalField(
                        decimal_places=2, default=50.0, max_digits=6
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        default=store_settings.models.get_default_store,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shipping_settings",
                        to="store_settings.storesettings",
                    ),
                ),
            ],
            options={
                "verbose_name": "Shipping Settings",
                "verbose_name_plural": "Shipping Settings",
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enable_2fa", models.BooleanField(default=False)),
                (
                    "logout_other_sessions",
                    models.BooleanField(default=False),
                ),
                ("notify_change", models.BooleanField(default=True)),
                ("enable_dark_mode", models.BooleanField(default=False)),
                ("enable_notifications", models.BooleanField(default=True)),
                ("password_autofill", models.BooleanField(default=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
