# Generated by Django 5.1.2 on 2025-01-30 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ShippingSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "shipping_options",
                    models.IntegerField(
                        choices=[
                            (1, "Standard Shipping"),
                            (2, "Express Shipping"),
                            (3, "Free Shipping"),
                        ],
                        default=1,
                    ),
                ),
                (
                    "standard_shipping_cost",
                    models.DecimalField(decimal_places=2, default=5.0, max_digits=6),
                ),
                (
                    "free_shipping_threshold",
                    models.DecimalField(decimal_places=2, default=50.0, max_digits=6),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StoreSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "store_name",
                    models.CharField(default="Little Explorers", max_length=255),
                ),
                (
                    "store_logo",
                    models.ImageField(blank=True, null=True, upload_to="store_logos/"),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        default="IrishRoyals@example.com", max_length=254
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(default="+353000000000", max_length=20),
                ),
                ("currency", models.CharField(default="EUR", max_length=10)),
                ("enable_reviews", models.BooleanField(default=True)),
                ("enable_maintenance_mode", models.BooleanField(default=False)),
                ("enable_paypal", models.BooleanField(default=True)),
                ("enable_stripe", models.BooleanField(default=True)),
                ("enable_cash_on_delivery", models.BooleanField(default=True)),
                (
                    "shipping_options",
                    models.TextField(
                        default="Standard Shipping,Express Shipping,Free Shipping"
                    ),
                ),
            ],
            options={
                "verbose_name": "Store Settings",
                "verbose_name_plural": "Store Settings",
            },
        ),
    ]
