# Generated by Django 5.1.2 on 2025-01-30 10:05

import django.db.models.deletion
import store_settings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store_settings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="shippingsettings",
            name="store",
            field=models.ForeignKey(
                default=store_settings.models.get_default_store,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shipping_settings",
                to="store_settings.storesettings",
            ),
        ),
    ]
