# Generated by Django 5.1.2 on 2025-02-01 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store_settings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="storesettings",
            name="main_page_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="main_page_image/"
            ),
        ),
    ]
