# Generated by Django 5.1.2 on 2025-02-03 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store_settings", "0002_storesettings_main_page_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="storesettings",
            name="home_page_button",
            field=models.CharField(default="Discover More", max_length=20),
        ),
        migrations.AddField(
            model_name="storesettings",
            name="welcome_msg",
            field=models.CharField(default="Welcome to our store", max_length=255),
        ),
    ]
